<?php

namespace App\DataFixtures\Provider;

class AnimalProvider
{
    // Taleau de 100 animaux pour les fixtures.
    private $animal = [
        "Data",
        "Colby",
        "Optic",
        "Cluster",
        "Juan",
        "Preston",
        "Kaiser",
        "Nile",
        "Payton",
        "Sherlock",
        "Clyde",
        "Pinky",
        "Pecan",
        "Wizard",
        "Crash",
        "Quasar",
        "Kang",
        "Ford",
        "Bacardi",
        "Preston",
        "Gilbert",
        "Super",
        "Noah",
        "Cheddar",
        "Yoda",
        "Gunther",
        "Strike",
        "Link",
        "Twerp",
        "Moxie",
        "Gilligan",
        "Butler",
        "Sage",
        "Noreaga",
        "Finch",
        "Reeses",
        "Hot Dog",
        "Nile",
        "Nova",
        "Sherlock",
        "Scratch",
        "Tyrese",
        "Fidget",
        "Aesop",
        "Jango",
        "Pirate",
        "Ford",
        "Ming",
        "Wicket",
        "Alfredo",
        "Kodo",
        "Orchid",
        "Carrot",
        "Mozzarella",
        "Quasar",
        "Baltazar",
        "Kennedy",
        "Rosa",
        "Sassy",
        "Talia",
        "Micro",
        "Raisin",
        "Brisk",
        "Hazel",
        "Pong",
        "Fog",
        "Jinx",
        "Sasha",
        "Satay",
        "Acorn",
        "Bella",
        "Taffy",
        "Coy",
        "Treasure",
        "Nelly",
        "Galaga",
        "Zuni",
        "Shadow",
        "Corby",
        "Kuma",
        "Snyder",
        "Shelby",
        "Dank",
        "Mimi",
        "Faith",
        "Nala",
        "Dipper",
        "Jinx",
        "Licker",
        "Hex",
        "Faith",
        "Paris",
        "Pixie",
        "Pecan",
        "Abstract",
        "Salt",
        "Shaker",
        "Friend",
        "Jackson",
        "bistouquette"
    ];


    /**
     * Retourne un nom d'un animal au hasard
     */
    public function randAnimal()
    {
        return $this->animal[array_rand($this->animal)];
    }
}